### ISSUE TITLE
Attaching to target is unreliable

### ISSUE THREAD

**Issue by h4yn0nnym0u5e** [ftrias/TeensyDebug#17]
I'm using Arduino 1.8.15 and Teensyduino 1.56 on Windows 10 x64. To make life even trickier I have a couple of non-Teensy COM devices at COM5 and COM7, so with the Teensy 4.1 appearing as either COM3 or COM4+COM6 I'm giving TeensyDebug a hard time!

I've got pretty much all the debug options (take-over / dual / manual) to work eventually, but there seems to be a significant difficulty getting GDB connected in the first place. Even if I set manual device selection, I get something like this in the Arduino build console:

Traceback (most recent call last):   
  File "teensy_debug", line 470, in <module>  
  File "teensy_debug", line 393, in runGDB  
  File "teensy_debug", line 285, in getPort  
AttributeError: 'NoneType' object has no attribute 'group'  
[6412] Failed to execute script teensy_debug  
the selected serial port [6412] Failed to execute script teensy_debug  
 does not exist or your board is not connected  

It would be really helpful to:
- be able to specify the target COM port to connect to
- maybe add a bit of a (configurable?) delay to allow the USB to re-enumerate after the Teensy's been programmed

**Comment by h4yn0nnym0u5e** [comment]
Pretty sure this is fixed
